SELECT 
  Sinton.P1 AS SINTON_P1,
  MEP.P1 AS MEP_P1,
  PECVD.P1 AS PECVD_P1,
  Wet.P2 AS Wet_P2,
  MEP.PK AS MEP_PK,
  Sinton.PK AS Sinton_PK,
  PECVD.PK AS PECVD_PK,
  Wet.PK AS Wet_PK
FROM 
  Sinton 
JOIN MEP 
  ON Sinton_PK=MEP_PK 
JOIN PECVD 
  ON Sinton_PK=PECVD_PK 
JOIN Wet 
  ON Sinton_PK=Wet_PK
WHERE
  Sinton_P1>0.1 AND Wet_P2>0;